<?php

declare(strict_types=1);
/** @var Blue\Core\Authentication\Login $this */
?>
<main>
    <form method="post">
        <input type="hidden" name="token" value="<?= $this->token ?>">
        <fieldset>
            <p>
                <label for="username">Username</label>
                <input type="text" name="username" id="username">
            </p>
            <p>
                <label for="password">Password</label>
                <input type="password" name="password" id="password">
            </p>
            <button type="submit">
                Login
            </button>
        </fieldset>
    </form>
</main>