version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8081:8025'

    mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=snappy
            - MYSQL_DATABASE=snappy
            - MYSQL_USER=snappy
            - MYSQL_PASSWORD=snappy
        ports:
            - '8083:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: .docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        extra_hosts:
          - host.docker.internal:host-gateway
        environment:
          PHP_IDE_CONFIG: "serverName=snappy"
        expose:
          - 9000
          - 9003
    yarn:
        image: node:16.19.1-alpine
        working_dir: /application
        command:
          - /bin/sh
          - -c
          - |
            yarn install
            yarn watch
        volumes:
          - '.:/application'
