<header>
    <h1>Oops!</h1>
</header>
<main>
    <svg
        width="100%"
        height="5rem"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
    >
        <use href="/icons.svg#file"></use>
    </svg>
    <h2>Page Not Found</h2>
    <p>The page you’re looking for can’t be found. Try going back to the previous page or verify that you navigated to a valid URL.</p>
</main>
<footer>
    <a href="<?= $this->basePath ?? '/' ?>">Home</a>
</footer>

