<?php return \Blue\Models\Analytics\Tracker\Entry::__set_state([
    'id' => '63d7cd780b845',
    'timestamp' => 1674818176,
    'requestId' => '63d3b280508a4',
    'timestampUnload' => null,
    'userId' => '',
    'sessionId' => 's-63d3b2804f26a',
    'sessionLanguage' => 'en',
    'headerLocale' => 'de_DE',
    'headerLanguage' => 'de',
    'headerRegion' => 'DE',
    'userAgent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15',
    'host' => 'live.sonice.at.construct.blue',
    'path' => '/',
    'referrer' => 'construct.blue/',
    'utmSource' => '',
    'utmMedium' => '',
    'utmCampaign' => '',
    'utmTerm' => '',
    'utmContent' => '',
    'statusCode' => 200,
    'reasonPhrase' => 'OK',
    'clickHref' => '',
    'clientHints' => \Blue\Models\Analytics\Tracker\ClientHints::__set_state([
        'architecture' => '',
        'bitness' => '',
        'mobile' => false,
        'model' => '',
        'platform' => '',
        'platformVersion' => '',
        'uaFullVersion' => '',
        'fullVersionList' => [],
        'app' => ''
    ])
]);
