<?php return \Blue\Models\Analytics\Tracker\Entry::__set_state([
    'id' => '63d7cd77ee228',
    'timestamp' => 1674388878,
    'requestId' => '63cd258e1d618',
    'timestampUnload' => null,
    'userId' => '',
    'sessionId' => 's-63cd258e1c62a',
    'sessionLanguage' => 'en',
    'headerLocale' => 'de_DE',
    'headerLanguage' => 'de',
    'headerRegion' => 'DE',
    'userAgent' => 'Safari/18614.3.7.1.5 CFNetwork/1402.0.8 Darwin/22.2.0',
    'host' => 'live.sonice.at.construct.blue',
    'path' => '/apple-touch-icon.png',
    'referrer' => '',
    'utmSource' => '',
    'utmMedium' => '',
    'utmCampaign' => '',
    'utmTerm' => '',
    'utmContent' => '',
    'statusCode' => 200,
    'reasonPhrase' => 'OK',
    'clickHref' => '',
    'clientHints' => \Blue\Models\Analytics\Tracker\ClientHints::__set_state([
        'architecture' => '',
        'bitness' => '',
        'mobile' => false,
        'model' => '',
        'platform' => '',
        'platformVersion' => '',
        'uaFullVersion' => '',
        'fullVersionList' => [],
        'app' => ''
    ])
]);
