<?php

$current = $current ?? null;
$url = $url ?? null;

?>

<main>
    <?php if (isset($current)): ?>

        <fieldset>
            <legend>Registered</legend>
            <?= $current ?>
        </fieldset>
    <?php endif; ?>
    <form is="tesla-setup" method="post" data-popup-url="<?= $url ?>">
        <label for="url">URL</label>
        <input id="url" type="text" name="url">
        <button type="submit">Login</button>
    </form>
</main>
